### ISSUE TITLE
AccountCaptcha Error

### ISSUE THREAD

**Issue by pavankatti** [9b/google-alerts#10]
Facing this issue after authentication .

File "/usr/local/lib/python2.7/dist-packages/google_alerts/__init__.py", line 295, in authenticate
raise AccountCaptcha('Google is forcing a CAPTCHA. To get around this issue, authenticate within your web browser, pass the CAPTCHA and try to run this script again. Once authenticated, this module will cache your session and load that in the future')
google_alerts.AccountCaptcha: Google is forcing a CAPTCHA. To get around this issue, authenticate within your web browser, pass the CAPTCHA and try to run this script again. Once authenticated, this module will cache your session and load that in the future

Please fix it!!

**Comment by 9b** [comment]
See #11 .
