### ISSUE TITLE
Invalid Credentials Error on New Accounts

### ISSUE THREAD

**Issue by achernob** [9b/google-alerts#11]
Hi,

Firstly, I just wanted to thank you for making this code. It has been a tremendous help and I use it quite frequently. I have never had the issue that I am having now and just wanted to ask you directly since it doesn't seem to be addresses in prior Invalid Credentials questions.

I am getting the error message below when trying to authenticate a **newly created** account on Google. I have previously used your code extensively, but I am now not able to authenticate even though the credentials are indeed correct (verified several times via chrome). I've tried numerous debugging routes, including creating another account to try the same thing ... as well as creating a few manual alerts via chrome before trying to authenticate. Nothing seems to work. What's most curious, is that I **am** able to authenticate all the other users with no problem.. but those users have had accounts for months. Could your code not be working on recently created google accounts?

Thank you very much!

`Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    ga.authenticate()
  File "C:\Users\achernobelskiy\AppData\Local\Programs\Python\Python36-32\lib\site-packages\google_alerts\google_alerts.py", line 158, in authenticate
    raise InvalidCredentials("Email or password was incorrect.")
google_alerts.google_alerts.InvalidCredentials: Email or password was incorrect.`

**Comment by 9b** [comment]
Thank you for the kudos. I've tested this with Google's new authentication flows and it does work for me, however, that does not mean it will always work for everyone. Google seems to spawn a checkpoint on a number of external factors when a user attempts to authenticate. I suspect your account is getting flagged for whatever reason and thus there's no good way to get past the issue. The only work around is an insecure use of copying your session cookie and seeding the file. I would only advocate this practice if you had an account dedicated to alerts and was not linked to a production account.

**Comment by dmoreno1994** [comment]
The same problem here. I'm going to try this solution: 

> The only work around is an insecure use of copying your session cookie and seeding the file

Thank you for your work.

**Comment by 9b** [comment]
I just pushed a new version to address the authentication issues. You can now run a `seed` switch in order to bring up a live session that will automate the login process and seed the session file with a valid ID. Let me know if this solves your issues!

**Comment by pylesage** [comment]
Hi, 
It works for me. 
Thanks

**Comment by 9b** [comment]
Magical!

**Comment by achernob** [comment]
Hi Brandon - I have two quick follow up questions ..wasn't sure whether I
should start a new thread or not

1) When trying to seed a login through the command prompt, I am getting the
following error: "Chrome version must be between 71 and 75." I suppose I
could back date my chrome version (77 right now), but is there a more
permanent solution? I presume that other folks will run into this soon as
well since Chrome typically auto-updates.

2) I'm a beginner, so sorry in advance if this is a silly question. About a
month ago (before my Chrome updated, I guess) I was successfully seeding a
session and also creating alerts on a given account strictly using the
command prompt. This helped me understand how to do everything from the
command prompt itself. My code, however, runs through a spreadsheet,
creates a dictionary of a bunch of alerts to create for several users, and
then logs into each account to create them in Python. I was originally able
to do this without the command prompt (since seeding a session wasn't
necessary - this is going back about a year now probably). Now, I somehow
need to call the command prompt from my Python script to seed a session in
the middle of my script when I am ready to upload that person's alerts. I
tried to understand how to do this using the web, but haven't found a way
to do it. To simplify the question, suppose you have a recently created
dictionary from an Excel workbook, where the alerts are in each row (e.g.
Row 1: "Tesla -Musk -Stock"; Row 2: "Ford - GM; etc) and you have the
user's login credentials. How would you then (1) call the command prompt to
seed that user's session, (2) create all the alerts (still in command
prompt?), and (3) exit out of the session / seed the next user.

Thank you SO much! This has been incredibly helpful and I deeply appreciate
your help and advice.
