### ISSUE TITLE
'InvalidCredentials: Email or password was incorrect' even if they are correct

### ISSUE THREAD

**Issue by GGChua01** [9b/google-alerts#13]
I have been using google-alerts for the past month everything was working as expected. Today, I experienced an error specifically when i try to use "authenticate()" on a GoogleAlerts object.

Whenever I attempt to use authenticate(), it throws an error saying:

`    raise InvalidCredentials("Email or password was incorrect.")

InvalidCredentials: Email or password was incorrect.`

Even when no change has been made to the my password or email.

I am on Python 3.6.

I have attempted what you have suggested to [previous issues](https://github.com/9b/google-alerts/issues/7) and saw that the unobfuscated password is correct.

Is there a workaround for this? Thank you!

**Comment by 9b** [comment]
Please update to the latest version and read the following, https://github.com/9b/google-alerts/wiki/Authentication-Flows

**Comment by 9b** [comment]
If you have a valid session, it should use that and not pass authentication. If you don't mind, message me on keybase and I can help troubleshoot. I'm not familiar with Spyder.

**Comment by GGChua01** [comment]
For anyone who might have the same problem, the GoogleAlerts class in the google_alerts.py seemed to have been modified/broken. 

Here are the steps I took to resolve the problem:
1) Replace the GoogleAlerts class in the google_alerts.py with the one from here https://github.com/9b/google-alerts/blob/master/google_alerts/__init__.py

2) Import the relevant packages in google_alerts.py (e.g. import os, pickle, etc.)

3) Copy the obfuscate function from the manage.py

I do not know what happened but this seems to have solved the problem for me.

Thank you @9b for your help!
