### ISSUE TITLE
Email or password was incorrect while using the library

### ISSUE THREAD

**Issue by assadvirgo** [9b/google-alerts#17]
**Describe the bug**
Not able to login using my email credentials. Always throw "Invalid Username / Password" However I put the correct credentials

**To Reproduce**
1. Installed the library
2. Following code was written in a file

from google_alerts import GoogleAlerts

ga = GoogleAlerts('cont****s@gmail.com', '****$')
ga.authenticate()

**Expected behavior**
Throws following error

Traceback (most recent call last):
  File "alerts.py", line 7, in <module>
    ga.authenticate()
  File "/Library/Python/2.7/site-packages/google_alerts/__init__.py", line 298, in authenticate
    raise InvalidCredentials("Email or password was incorrect.")
google_alerts.InvalidCredentials: Email or password was incorrect.

**Comment by 9b** [comment]
Please use the following:
https://github.com/9b/google-alerts/wiki/Authentication-Flows
