### ISSUE TITLE
Invalid credentials message is invalid for the authentication error

### ISSUE THREAD

**Issue by Nick-Morgan** [9b/google-alerts#18]
This is an issue that others have posted about ([7](https://github.com/9b/google-alerts/issues/7), [13](https://github.com/9b/google-alerts/issues/13))

The issue stems from the `authenticate` method of the `GoogleAlerts` class, specifically at the highlighted code below:

https://github.com/9b/google-alerts/blob/master/google_alerts/__init__.py#L292-L298

Here is the html of `response` via the code that I've highlighted:

![Screen Shot 2019-03-26 at 11 40 31 AM](https://user-images.githubusercontent.com/23083692/55016131-2eda1180-4fbc-11e9-9488-47bb35ab003d.png)

POST requests are done via HTTP, which is what's causing this issue. I "solved" this issue by using the CLI, passing the `seed` option, and using Chromedriver. However, I think `GoogleAlerts.authenticate` could be improved to suggest this route, instead of stating that the credentials are invalid.

**Comment by 9b** [comment]
Thanks for the feedback. Looks like Google had made some flow changes and this cropped up. I'll account for it to be clear.
