### ISSUE TITLE
Captcha: Does not open during "create"

### ISSUE THREAD

**Issue by sirnewbee** [9b/google-alerts#19]
I have already passed the installation and setup of google alerts. But, whenever I try to create a new monitor using:
`google-alerts create --term "hello world" --delivery 'rss' --frequency 'realtime' `

It gives me this error:
`google_alerts.AccountCaptcha: Google is forcing a CAPTCHA. To get around this issue, run the google-alerts with the seed option to open an interactive authentication session. Once authenticated, this module will cache your session and load that in the future`

but does not open in any browser or my current browser.

How do I run with seed option? Or open the captcha on my browser?

**Comment by 9b** [comment]
https://github.com/9b/google-alerts/wiki/Authentication-Flows

**Comment by sirnewbee** [comment]
Hello.

Thank you so much for the quick reply.

Best regards,
Kawin Cheong
