### ISSUE TITLE
State was not properly obtained from the app

### ISSUE THREAD

**Issue by taborlin5** [9b/google-alerts#20]
I successfully used google-alerts to create ~64 alerts. I was rate limited by Google and had to re-enter a Captcha. I'm able to log into Google Alerts and see the Alerts I created.

However, when I try to list them using google-alerts list or ga.list() I get a "State was not properly obtained from the app" error.

I tried deleting both the config file and the session file and resetting and reseeding google-alerts, but I get the same error.

Any help would be appreciated.

**Comment by 9b** [comment]
Intriguing. Can you configure logging to `debug` and send me the line starting with `State value set`. It could be an edge-case I had not accounted for in the processing.

**Comment by taborlin5** [comment]
Thanks for your help. Not sure if this is what you are looking for:

from google_alerts import GoogleAlerts
ga = GoogleAlerts(***, ***)
ga.set_log_level('DEBUG')
ga.authenticate()
DEBUG __init__:_session_check():180 2019-06-05 18:02:10,080| Loaded cookies
from session file
DEBUG __init__:_process_state():220 2019-06-05 18:02:11,719| Capturing
state from the request
DEBUG __init__:authenticate():281 2019-06-05 18:02:12,436| [!] User has
already authenticated
ga.list()
---------------------------------------------------------------------------
InvalidState                              Traceback (most recent call last)
<ipython-input-8-81d5347b0d11> in <module>()
----> 1 ga.list()

c:\users\chggi\onedrive\desktop\projects\wavelength-app\env\lib\site-packages\google_alerts\__init__.py
in list(self, term)
    309         """List alerts configured for the account."""
    310         if not self._state:
--> 311             raise InvalidState("State was not properly obtained
from the app")
    312         self._process_state()
    313         if not self._state[1]:

InvalidState: State was not properly obtained from the app

**Comment by 9b** [comment]
Managed to replicate. Appears Google maxed out at 65 alerts for me before dumping a sever error. Are you able to still login and access the portal? If so, I suspect I need to wait a bit before I can truly test. Can you set your log_level to `debug` (lower case), then send again?

![Screen Shot 2019-06-05 at 6 10 33 PM](https://user-images.githubusercontent.com/505557/58994043-3f2d1a80-87bd-11e9-9e58-624ea7aaee22.png)

**Comment by taborlin5** [comment]
I can access https://www.google.com/alerts right now. I can delete / edit / add alerts.

The output seems to be the same when I change the debug casing:

ga.set_log_level('debug')
ga.list()
ga.authenticate()
DEBUG __init__:_session_check():180 2019-06-05 18:14:01,091| Loaded cookies from session file
DEBUG __init__:_process_state():220 2019-06-05 18:14:02,861| Capturing state from the request
DEBUG __init__:authenticate():281 2019-06-05 18:14:03,637| [!] User has already authenticated

ga.list()
---------------------------------------------------------------------------
InvalidState                              Traceback (most recent call last)
<ipython-input-6-81d5347b0d11> in <module>()
----> 1 ga.list()

XX\__init__.py in list(self, term)
    309         """List alerts configured for the account."""
    310         if not self._state:
--> 311             raise InvalidState("State was not properly obtained from the app")
    312         self._process_state()
    313         if not self._state[1]:

InvalidState: State was not properly obtained from the app

**Comment by 9b** [comment]
I will check on this tomorrow when they unblock me. If you'd like to try and help, throw a print statement of this line, https://github.com/9b/google-alerts/blob/master/google_alerts/__init__.py#L224 and send me the printed results.

**Comment by 9b** [comment]
Okay, unblocked and can add new alerts in without issues. I've added 100 alerts and my code is printing them. Let me know if you remain blocked by this tomorrow, and I can build a more detailed package that has better debug logging.

**Comment by taborlin5** [comment]
Thanks for your help - I'm unblocked and able to use it. Really like your work!

**Comment by GabrielLaw** [comment]
@9b I'm running into this same exact issue

**Comment by saksarip** [comment]
Hello, I'm just started trying to use the google-alerts library and am running into the same issue. 
Here is my code 
`from google_alerts import GoogleAlerts

#Creating an instance
ga = GoogleAlerts('*****', '*****')

#Authenticate
ga.set_log_level('DEBUG')
ga.authenticate()

#ga.list()

#Add a new monitor
ga.create("Hello World", {'delivery': 'RSS'})`

Here is my output
DEBUG __init__:_session_check():185 2020-12-23 12:53:24,818| Loaded cookies from session file
DEBUG __init__:_process_state():225 2020-12-23 12:53:25,315| Capturing state from the request
Traceback (most recent call last):
  File "/Users/sakethsaripalli/PycharmProjects/InfoBot/Scraping/DataGathering.py", line 13, in <module>
    ga.create("Hello World", {'delivery': 'RSS'})
  File "/Users/sakethsaripalli/PycharmProjects/InfoBot/venv/lib/python3.8/site-packages/google_alerts/__init__.py", line 367, in create
    raise InvalidState("State was not properly obtained from the app")
google_alerts.InvalidState: State was not properly obtained from the app
DEBUG __init__:authenticate():291 2020-12-23 12:53:25,779| [!] User has already authenticated

**Comment by 9b** [comment]
Tested with my standard user and did not have an issue. Have you seeded your account session using the chromedrive process? If not, look at the readme for details. State will not be set until this is completed.

**Comment by saksarip** [comment]
The account session was seeded with my chrome driver. I'm still receiving this error.

**Comment by 9b** [comment]
Can you run in debug and send me the details?
