### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by virajdeokar** [9b/google-alerts#21]
I just started using google-alerts. When trying to authenticate my sign in I get the following:
`JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

I'm not sure why this is happening. I had to seed my session to get around the CAPTCHA issue which seemed to work properly.

Here is the traceback:

![image](https://user-images.githubusercontent.com/29486782/60824410-38c20200-a1b2-11e9-8a45-4f3ee682ec01.png)

**Comment by p4lsec** [comment]
I'm also experiencing this error on both Windows 10 and Linux.

**Comment by 9b** [comment]
Google made a change to their underlying configuration structure which broke my scraping. This is now fixed in 0.2.2.

**Comment by virajdeokar** [comment]
Thanks. Looks like when fixing the code you added a comma by accident here:
![image](https://user-images.githubusercontent.com/29486782/61203964-8e3b6900-a6f4-11e9-808b-14b42a156cdf.png)

**Comment by virajdeokar** [comment]
I just changed that line to `except Exception`. It occurs on another line as well.

**Comment by 9b** [comment]
Fixed, apologize for that!
