### ISSUE TITLE
 Rate limited by Google

### ISSUE THREAD

**Issue by p4lsec** [9b/google-alerts#25]
It looks like Google is rate-limiting queries.  When I run my script, I get the following:

`Traceback (most recent call last):
  File "C:\Users\user\Downloads\gAlertsFormatter.py", line 37, in <module>
    ga.create('Google'google_alerts\__init__.py", line 377, in create
    % response.content)
google_alerts.ActionError: Failed to create monitor: b'<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"/><title>Sorry...</title><style> body { font-family: verdana, arial, sans-serif; background-color: #fff; color: #000; }</style></head><body><div><table><tr><td><b><font face=sans-serif size=10><font color=#4285f4>G</font><font color=#ea4335>o</font><font color=#fbbc05>o</font><font color=#4285f4>g</font><font color=#34a853>l</font><font color=#ea4335>e</font></font></b></td><td style="text-align: left; vertical-align: bottom; padding-bottom: 15px; width: 50%"><div style="border-bottom: 1px solid #dfdfdf;">Sorry...</div></td></tr></table></div><div style="margin-left: 4em;"><h1>We\'re sorry...</h1><p>... but your computer or network may be sending automated queries. To protect our users, we can\'t process your request right now.</p></div><div style="margin-left: 4em;">See <a href="https://support.google.com/websearch/answer/86640">Google Help</a> for more information.<br/><br/></div><div style="text-align: center; border-top: 1px solid #dfdfdf;"><a href="https://www.google.com">Google Home</a></div></body></html>'
[Finished in 31.3s]`

Is it possible to limit the amount of requests sent out per second? Or to otherwise incorporate some kind of rate-limiting measure?  Thanks for your hard work on everything!

**Comment by 9b** [comment]
I've hit this once before, but it's note entirely clear what the rate is that can't be tripped. I can better handle the error, but I don't consider this to be a bug in the core. If implementing this library in a script,  I would just place a sleep timer in between each create action.

**Comment by p4lsec** [comment]
Right on.  And you're right, I should have submitted this as a feature request.  My apologies.

**Comment by 9b** [comment]
Happy to keep this open under the note that this will be a bugfix to better account for rate limiting!

**Comment by p4lsec** [comment]
I was unable to work around this by using fireprox and creating a gateway to send requests from different URLs. They must be limiting by account activity (regardless of IP).

**Comment by p4lsec** [comment]
Just an update, I was able to write a quick script that creates a .txt file with a command on each line, and then run `cmd < file.txt` to submit a new request for each entry.  This worked but was a bit slower.  Example of the .txt file:

`google-alerts create --term "test 1" --delivery mail --frequency realtime
google-alerts create --term "test 2" --delivery mail --frequency realtime
google-alerts create --term "test 3" --delivery mail --frequency realtime`
