### ISSUE TITLE
Set "match_type" = 'ALL' on creation of a new monitor.

### ISSUE THREAD

**Issue by gprmarquez** [9b/google-alerts#27]
Would this be possible?

**Comment by gprmarquez** [comment]
Also, would it be possible to bulk upload alerts? And to bulk receive RSS links?

**Comment by 9b** [comment]
Do you mean turning all on by default?

**Comment by gprmarquez** [comment]
Hi, yes. Turning the “all” option all by default is what I meant by the first comment.
