### ISSUE TITLE
Can't create new monitors

### ISSUE THREAD

**Issue by jacopone** [9b/google-alerts#29]
**Describe the bug**
After correctly authenticating and importing the module, when I try to create a new monitor following the instructions in the quickstart it seems it seems it's not creating them when I select the mail delivery method, it breaks when I select the RSS delivery method.

It seems I correctly authenticated, and I remember using this module perfectly a while ago, for sure a month ago.

Thanks for your work

google-alerts create --term "hello world" --delivery 'mail' --frequency 'realtime'
DEBUG __init__:_config_bootstrap():156 2019-12-13 13:28:31,355| Caching authentication in config file
DEBUG __init__:_session_check():185 2019-12-13 13:28:31,356| Loaded cookies from session file
DEBUG __init__:_process_state():225 2019-12-13 13:28:31,825| Capturing state from the request
DEBUG __init__:_process_state():235 2019-12-13 13:28:33,005| State value set: [None, [None, None, [None, 'com', ['en', 'US']], None, 3, [[1, '', [None, 12], 2, 'en-US', None, None, None, None, None, '0', None, None, 'AB2Xq4hcilCERh73EFWJVHXx-io2lhh1EhC8UD8']]], '', None, None, [[[None, None, 2]]]]
DEBUG __init__:authenticate():291 2019-12-13 13:28:33,005| [!] User has already authenticated
DEBUG __init__:create():371 2019-12-13 13:28:33,005| Creating alert using: https://www.google.com/alerts/create?x=
DEBUG __init__:_process_state():225 2019-12-13 13:28:33,064| Capturing state from the request
DEBUG __init__:_process_state():235 2019-12-13 13:28:33,901| State value set: [None, [None, None, [None, 'com', ['en', 'US']], None, 3, [[1, '', [None, 12], 2, 'en-US', None, None, None, None, None, '0', None, None, 'AB2Xq4hcilCERh73EFWJVHXx-io2lhh1EhC8UD8']]], '', None, None, [[[None, None, 2]]]]
INFO  __init__:list():336 2019-12-13 13:28:33,901| No monitors have been created yet.

 google-alerts create --term "hello world" --delivery 'rss' --frequency 'realtime'
DEBUG __init__:_config_bootstrap():156 2019-12-13 13:35:58,140| Caching authentication in config file
DEBUG __init__:_session_check():185 2019-12-13 13:35:58,141| Loaded cookies from session file
DEBUG __init__:_process_state():225 2019-12-13 13:35:58,632| Capturing state from the request
DEBUG __init__:_process_state():235 2019-12-13 13:35:59,828| State value set: [None, [None, None, [None, 'com', ['en', 'US']], None, 3, [[1, '', [None, 12], 2, 'en-US', None, None, None, None, None, '0', None, None, 'AB2Xq4hcilCERh73EFWJVHXx-io2lhh1EhC8UD8']]], '', None, None, [[[None, None, 2]]]]
DEBUG __init__:authenticate():291 2019-12-13 13:35:59,828| [!] User has already authenticated
DEBUG __init__:create():371 2019-12-13 13:35:59,828| Creating alert using: https://www.google.com/alerts/create?x=
Traceback (most recent call last):
  File "/home/guyfawkes/.local/share/virtualenvs/google-alerts-TMwFacs7/bin/google-alerts", line 8, in <module>
    sys.exit(main())
  File "/home/guyfawkes/.local/share/virtualenvs/google-alerts-TMwFacs7/lib/python3.7/site-packages/google_alerts/cli/manage.py", line 165, in main
    'exact': args.exact})
  File "/home/guyfawkes/.local/share/virtualenvs/google-alerts-TMwFacs7/lib/python3.7/site-packages/google_alerts/__init__.py", line 377, in create
    % response.content)
google_alerts.ActionError: Failed to create monitor: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 500 (Server Error)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>500.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The server encountered an error and could not complete your request.<p>If the problem persists, please <A HREF="http://www.google.com/support/">report</A> your problem and mention this error message and the query that caused it.  <ins>That\xe2\x80\x99s all we know.</ins>\n'

I'm running Ubuntu 18.04.3 LTS, using python 3.7.3

**Comment by 9b** [comment]
Tested my setup end-to-end and it's working okay. Please seed your session with the proper chrome driver using this documentation. https://github.com/9b/google-alerts/wiki/Authentication-Flows

**Comment by jacopone** [comment]
I tried to seed my session according to the instructions provided. 
It gives me a message saying - translating from Italian: "Impossible to log in. This browser or app might not be secure. Try to use another browser. If you are using already a supported browser you can try to update the screen and try to login again." 
Here is the log:
(google-alerts) guyfawkes@linux-box:~/credimi_repos/google-alerts$ google-alerts seed --driver chromedriver_linux64/chromedriver 
DEBUG __init__:_config_bootstrap():156 2020-01-17 17:25:30,130| Caching authentication in config file
[*] Filled in email address and submitted.
[*] Filled in password and submitted.
[!] Waiting for the authentication cookie or 20 seconds
[$] Session has been seeded, google-alerts is ready for use.
![Screenshot from 2020-01-17 17-25-42](https://user-images.githubusercontent.com/828254/72629334-67364c00-3950-11ea-97dc-ad21f8338ab2.png)

**Comment by jacopone** [comment]
FYI - tried again installing the library without pip and without using pipenv, which I was using before, but still returns authentications problems even with seeding. The library returns that it correctly acquired the  session cookie and that the session have been seeded, but it the page returns a signin/reject page as shown above. I tried to google a bit the error and found these interesting pages : https://help.applitools.com/hc/en-us/articles/360007189411--Chrome-is-being-controlled-by-automated-test-software-notification  https://stackoverflow.com/questions/59534028/sign-in-to-gmail-account-fails-selenium-automation   I even tried to Allow less secure apps on my account but it's still not working. I tried to download and use chrome version 79 but still not working. 
Thanks!

**Comment by IskanderBlue** [comment]
I'm seeing errors identical to the initial post.  
Same results after updating Chrome and using the most appropriate chromedriver.  .  

[Also, in order to 'seed' properly, I had to change line 128 of ...site-packages/google_alerts/cli/manage.py to 
`inputElement = driver.find_element_by_name('password') `]

**Comment by caballeto** [comment]
> I'm seeing errors identical to the initial post.
> Same results after updating Chrome and using the most appropriate chromedriver. .
> 
> [Also, in order to 'seed' properly, I had to change line 128 of ...site-packages/google_alerts/cli/manage.py to
> `inputElement = driver.find_element_by_name('password') `]

Have you managed to solve the problem?

**Comment by IskanderBlue** [comment]
> > I'm seeing errors identical to the initial post.
> > Same results after updating Chrome and using the most appropriate chromedriver. .
> > [Also, in order to 'seed' properly, I had to change line 128 of ...site-packages/google_alerts/cli/manage.py to
> > `inputElement = driver.find_element_by_name('password') `]
> 
> Have you managed to solve the problem?

No; gave up on using google-alerts, which is unfortunate because it would have been a better solution than what I did end up implementing.

**Comment by caballeto** [comment]
> > > I'm seeing errors identical to the initial post.
> > > Same results after updating Chrome and using the most appropriate chromedriver. .
> > > [Also, in order to 'seed' properly, I had to change line 128 of ...site-packages/google_alerts/cli/manage.py to
> > > `inputElement = driver.find_element_by_name('password') `]
> > 
> > 
> > Have you managed to solve the problem?
> 
> No; gave up on using google-alerts, which is unfortunate because it would have been a better solution than what I did end up implementing.

Could you tell a bit more about it? I am thinking of building social media and web analytics tool, this library seemed to be a good start. Now, I can think only about using APIs for certain platforms like Twitter and Facebook, and see no solution for everything else like blogs, forums, etc. Maybe you could advise anything?

**Comment by IskanderBlue** [comment]
> Could you tell a bit more about it? I am thinking of building social media and web analytics tool, this library seemed to be a good start. Now, I can think only about using APIs for certain platforms like Twitter and Facebook, and see no solution for everything else like blogs, forums, etc. Maybe you could advise anything?

My use case was for a news feed.  
I ended up using something from https://rapidapi.com/category/News%2C%20Media and tried to limit new searches to results starting from the last time the search was run.  

Perhaps, depending on the volume of searches you're expecting to perform (or your willingness to pay), you can find some other API that will work for you (eg. google search).

**Comment by Minus-Sinus** [comment]
> I tried to seed my session according to the instructions provided.
> It gives me a message saying - translating from Italian: "Impossible to log in. This browser or app might not be secure. Try to use another browser. If you are using already a supported browser you can try to update the screen and try to login again."
> Here is the log:
> (google-alerts) guyfawkes@linux-box:~/credimi_repos/google-alerts$ google-alerts seed --driver chromedriver_linux64/chromedriver
> DEBUG **init**:_config_bootstrap():156 2020-01-17 17:25:30,130| Caching authentication in config file
> [_] Filled in email address and submitted. [_] Filled in password and submitted.
> [!] Waiting for the authentication cookie or 20 seconds
> [$] Session has been seeded, google-alerts is ready for use.
> ![Screenshot from 2020-01-17 17-25-42](https://user-images.githubusercontent.com/828254/72629334-67364c00-3950-11ea-97dc-ad21f8338ab2.png)

I had the same issue - the selenium login showed a 2-factor-authentication screen asking for a SMS confirmation code. Even if I managed to type it in fast enough, the seeding did not work. Did also not work when I turned off 2-factor notification.

Solution that worked for me: Create a "fresh" google account and enter no mobile number. Then I was able to do the seeding successfully.
