### ISSUE TITLE
Creating alerts with alert_frequency AS_IT_HAPPENS

### ISSUE THREAD

**Issue by jrhode** [9b/google-alerts#3]
I am having trouble adding alerts with alert_frequency AS_IT_HAPPENS. When I try to do this, an empty list is returned and the alert doesn't show up on Google. I've played around a bit, and the only alert_frequency that creates an alert is the default, AT_MOST_ONCE_A_DAY.

**Comment by 9b** [comment]
Sorry, I was delayed on this. I found the issue with the strange formatting Google wanted, but I had overlooked. Tested this with all types and had success. I also added an option on the command line, so you can select the frequency when creating. See the commit for more details.
