### ISSUE TITLE
Modifications required for the library to work on Python 3.8 

### ISSUE THREAD

**Issue by tonydspaniard** [9b/google-alerts#31]
First of all, I would like to thank you for developing this library and provide it as open source to everybody. 

I would like to expose certain issues that I had using your library and how I made it work: 

*Issue*
**Unable to make use of the library within a docker image**

*Solution*
Simply install the library (together with selenium) using pip, make sure you have the latest chromedriver installed on your machine and then follow the steps to create the `session` file. 

It is very important that you logout from all the google accounts, and make use of the username + password of that account you wish to use. Please, make sure the computer you are going to use to create the `session` file is on an authorized and recognized computer, otherwise Google will ask for a code thus breaking the flow of the code. 

After, collect the files `config.json` and `session` and add it to your docker container to the path you wish the library to work (remember to update those paths within the code of the library). It will work like a charm. 

*Issue* 
**When seeding it was failing due to that chromedriver didn't accept the certificate**

*Solution*
I added the following code on `manage.py`file: 
```python 
    # previous code
    if args.cmd == 'seed':
        config['password'] = obfuscate(str(config['password']), 'fetch')
        ga = GoogleAlerts(config['email'], config['password'])
        chrome_options = webdriver.ChromeOptions()
        chrome_options.add_experimental_option("excludeSwitches", ['enable-automation'])
        caps = webdriver.DesiredCapabilities.CHROME.copy() 
        caps['acceptInsecureCerts'] = True # Accept insecure certificates!
        with contextlib.closing(webdriver.Chrome(args.driver, desired_capabilities=caps, options=chrome_options)) as driver:
               # .... code continues here
``` 
*Issue* 
**window.STATE value was not properly collected: State was not properly obtained from the app**

*Solution*
Looking at the code I saw that the value of the javascript variable `window.STATE` was not properly collected. I had to change the `_process_state` function so to extract the value using regex: 
```python
import re 

# code here ... 
class GoogleAlerts:

    # more code here ...

    def _process_state(self):
        """Process the application state configuration.

        Google Alerts manages the account information and alert data through
        some custom state configuration. Not all values have been completely
        enumerated.
        """
        self._log.debug("Capturing state from the request")
        response = self._session.get(url=self.ALERTS_URL, headers=self.HEADERS)
        soup = BeautifulSoup(response.content, "html.parser")
        p = re.compile('window.STATE=(.*);')  # make use of regex! 
        for i in soup.findAll('script', {'src': False}): # scripts with external javascript should not be used!
            if not p.search(i.string): # i.text was returning empty, make use of i.string instead!
                continue
            try:
                match = p.search(i.string)
                state = json.loads(match.group(0)[13:-6]) # extract the value of the variable
                if state != "":
                    self._state = state
                    self._log.debug("State value set: %s" % self._state)
            except Exception as e:
                raise StateParseFailure(
                    "Google has changed their core protocol and a new parser must be built. Please file a bug at https://github.com/9b/google-alerts/issues.")
        return self._state
```

**Python Version** Python 3.8.2

Hope this helps someone going throughout the same problems

**Comment by 9b** [comment]
Hey, thanks a lot for posting this detailed feedback. Would you be willing to submit a pull request with the changes and docker updates you made? I can review them completely, test that they work without issues and am happy to merge it for everyones benefit.

**Comment by tonydspaniard** [comment]
@9b I didn't do it because I don't know if my case is due to a certain python version and/or docker issue. The fact that you had `i.text` vs `i.string` made me wonder. 

But I will be more than happy to help.

**Comment by 9b** [comment]
Hook me up with a PR!

**Comment by tonydspaniard** [comment]
Apologies @9b I have been highly stressed with work. Will push in a couple of hours if you don't mind.

**Comment by 9b** [comment]
Thank you so much and I am sorry to hear about the stress at work.
Hopefully it dies down or you can catch a break.

**Comment by Chuwiey** [comment]
Ran into similar issues as described above with python 3.8 and the pip installed version. Any plans to update pypi to latest master version? Thanks!

**Comment by 9b** [comment]
Can you be more specific on the exact issue you're experiencing? The suggestions above were merged via PR some time ago.
