### ISSUE TITLE
invalid state error

### ISSUE THREAD

**Issue by ragramrm** [9b/google-alerts#33]
I am getting invalid state error when I am executing ga.list()

[1;32mDEBUG __init__:_config_bootstrap():156 2020-09-09 11:12:05,863[0m| Caching authentication in config file
[1;32mDEBUG __init__:_session_check():184 2020-09-09 11:12:05,870[0m| Loaded cookies from session file
[1;32mDEBUG __init__:_process_state():222 2020-09-09 11:12:08,728[0m| Capturing state from the request
[1;32mDEBUG __init__:authenticate():291 2020-09-09 11:12:11,436[0m| [!] User has already authenticated
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    ga.list()
  File "C:\Users\ragavendran.ramesh\AppData\Local\Programs\Python\Python38\lib\site-packages\google_alerts\__init__.py", line 331, in list
    raise InvalidState("State was not properly obtained from the app")
google_alerts.InvalidState: State was not properly obtained from the app

**Comment by 9b** [comment]
You need to ensure your session has been seeded appropriately. I just checked the flow end-to-end with my test account and was able to confirm that everything is working.
