### ISSUE TITLE
Authentication is blocked after the step enter email address 

### ISSUE THREAD

**Issue by Micki-El** [9b/google-alerts#37]
**Describe the bug**
Hi, 

the authentication does not work anymore. 
When I run cli seed command, Google blocks me right after the email address was entered displaying the following
![image](https://user-images.githubusercontent.com/81301270/112299687-51c95a00-8c98-11eb-9d46-e600869317b2.png)

After that the windows closes and I get an exception that selenium could not find a window for entering password:

selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id ="password"]/div[1]/div / div[1]/input"}

Authentication using Python script also doesn't work anymore.  Running ga.authenticate() I get the following:

DEBUG __init__:_session_check():185 2021-03-24 11:06:16,840| Loaded cookies from session file
DEBUG __init__:_session_check():185 2021-03-24 11:06:16,840| Loaded cookies from session file
DEBUG __init__:_session_check():185 2021-03-24 11:06:16,840| Loaded cookies from session file
DEBUG __init__:_session_check():185 2021-03-24 11:06:16,840| Loaded cookies from session file
DEBUG __init__:_session_check():185 2021-03-24 11:06:16,840| Loaded cookies from session file
DEBUG __init__:_session_check():185 2021-03-24 11:06:16,840| Loaded cookies from session file
DEBUG __init__:_session_check():185 2021-03-24 11:06:16,840| Loaded cookies from session file
DEBUG __init__:_session_check():185 2021-03-24 11:06:16,840| Loaded cookies from session file
DEBUG __init__:_session_check():185 2021-03-24 11:06:16,840| Loaded cookies from session file
DEBUG __init__:_process_state():225 2021-03-24 11:06:17,497| Capturing state from the request
DEBUG __init__:_process_state():225 2021-03-24 11:06:17,497| Capturing state from the request
DEBUG __init__:_process_state():225 2021-03-24 11:06:17,497| Capturing state from the request
DEBUG __init__:_process_state():225 2021-03-24 11:06:17,497| Capturing state from the request
DEBUG __init__:_process_state():225 2021-03-24 11:06:17,497| Capturing state from the request
DEBUG __init__:_process_state():225 2021-03-24 11:06:17,497| Capturing state from the request
DEBUG __init__:_process_state():225 2021-03-24 11:06:17,497| Capturing state from the request
DEBUG __init__:_process_state():225 2021-03-24 11:06:17,497| Capturing state from the request
DEBUG __init__:_process_state():225 2021-03-24 11:06:17,497| Capturing state from the request
DEBUG __init__:_process_state():235 2021-03-24 11:06:22,659| State value set: [None, [None, None, [None, 'com', ['en', 'US']], None, 3, [[1, '', [None, 10], 2, 'en-US', None, None, None, None, None, '0', None, None, 'AB2Xq4hcilCERh73EFWJVHXx-io2lhh1EhC8UD8']]], '', None, None, [[[None, None, 2]]]]
DEBUG __init__:_process_state():235 2021-03-24 11:06:22,659| State value set: [None, [None, None, [None, 'com', ['en', 'US']], None, 3, [[1, '', [None, 10], 2, 'en-US', None, None, None, None, None, '0', None, None, 'AB2Xq4hcilCERh73EFWJVHXx-io2lhh1EhC8UD8']]], '', None, None, [[[None, None, 2]]]]
DEBUG __init__:_process_state():235 2021-03-24 11:06:22,659| State value set: [None, [None, None, [None, 'com', ['en', 'US']], None, 3, [[1, '', [None, 10], 2, 'en-US', None, None, None, None, None, '0', None, None, 'AB2Xq4hcilCERh73EFWJVHXx-io2lhh1EhC8UD8']]], '', None, None, [[[None, None, 2]]]]
DEBUG __init__:_process_state():235 2021-03-24 11:06:22,659| State value set: [None, [None, None, [None, 'com', ['en', 'US']], None, 3, [[1, '', [None, 10], 2, 'en-US', None, None, None, None, None, '0', None, None, 'AB2Xq4hcilCERh73EFWJVHXx-io2lhh1EhC8UD8']]], '', None, None, [[[None, None, 2]]]]
DEBUG __init__:_process_state():235 2021-03-24 11:06:22,659| State value set: [None, [None, None, [None, 'com', ['en', 'US']], None, 3, [[1, '', [None, 10], 2, 'en-US', None, None, None, None, None, '0', None, None, 'AB2Xq4hcilCERh73EFWJVHXx-io2lhh1EhC8UD8']]], '', None, None, [[[None, None, 2]]]]
DEBUG __init__:_process_state():235 2021-03-24 11:06:22,659| State value set: [None, [None, None, [None, 'com', ['en', 'US']], None, 3, [[1, '', [None, 10], 2, 'en-US', None, None, None, None, None, '0', None, None, 'AB2Xq4hcilCERh73EFWJVHXx-io2lhh1EhC8UD8']]], '', None, None, [[[None, None, 2]]]]
DEBUG __init__:_process_state():235 2021-03-24 11:06:22,659| State value set: [None, [None, None, [None, 'com', ['en', 'US']], None, 3, [[1, '', [None, 10], 2, 'en-US', None, None, None, None, None, '0', None, None, 'AB2Xq4hcilCERh73EFWJVHXx-io2lhh1EhC8UD8']]], '', None, None, [[[None, None, 2]]]]
DEBUG __init__:_process_state():235 2021-03-24 11:06:22,659| State value set: [None, [None, None, [None, 'com', ['en', 'US']], None, 3, [[1, '', [None, 10], 2, 'en-US', None, None, None, None, None, '0', None, None, 'AB2Xq4hcilCERh73EFWJVHXx-io2lhh1EhC8UD8']]], '', None, None, [[[None, None, 2]]]]
DEBUG __init__:_process_state():235 2021-03-24 11:06:22,659| State value set: [None, [None, None, [None, 'com', ['en', 'US']], None, 3, [[1, '', [None, 10], 2, 'en-US', None, None, None, None, None, '0', None, None, 'AB2Xq4hcilCERh73EFWJVHXx-io2lhh1EhC8UD8']]], '', None, None, [[[None, None, 2]]]]
DEBUG __init__:authenticate():291 2021-03-24 11:06:22,664| [!] User has already authenticated
DEBUG __init__:authenticate():291 2021-03-24 11:06:22,664| [!] User has already authenticated
DEBUG __init__:authenticate():291 2021-03-24 11:06:22,664| [!] User has already authenticated
DEBUG __init__:authenticate():291 2021-03-24 11:06:22,664| [!] User has already authenticated
DEBUG __init__:authenticate():291 2021-03-24 11:06:22,664| [!] User has already authenticated
DEBUG __init__:authenticate():291 2021-03-24 11:06:22,664| [!] User has already authenticated
DEBUG __init__:authenticate():291 2021-03-24 11:06:22,664| [!] User has already authenticated
DEBUG __init__:authenticate():291 2021-03-24 11:06:22,664| [!] User has already authenticated
DEBUG __init__:authenticate():291 2021-03-24 11:06:22,664| [!] User has already authenticated

Although it is written that the user has already authenticated, it is not truth because ga.list()  gives me the warning "No monitors have been created yet."  and in reality I have alerts under my account.

Could you please have a look at this issue?

Thanks in advance!

**Comment by 9b** [comment]
Please make sure your chromedriver used in seeding matches that of your current chrome installation, otherwise this error will show up.

**Comment by Micki-El** [comment]
I checked the chromedriver version and version of chrome. They are the same 89.0.4389.

**Comment by 9b** [comment]
Hmm. I’m not sure what to say. I was able to see the browser load, fill in
the details and seed the file.
