### ISSUE TITLE
email or password incorrect 

### ISSUE THREAD

**Issue by prakasharul** [9b/google-alerts#4]
when it is in live (aws + Django +apache) shows username and password incorrect. but locally working fine. @9b

**Comment by 9b** [comment]
Are you using the latest and can you share logs? I wonder if the AWS source is causing Google to throw a CAPTCHA. Upon successful authentication, the service will cache a cookie for reuse to avoid CAPTCHA. The logs should indicate why the failure is taking place at a more granular level.

**Comment by prakasharul** [comment]
`Traceback (most recent call last):
  File "/home/ubuntu/socialbook/sbfeeds/views.py", line 27, in googlefeeds
    auth = ga.authenticate()
  File "/home/ubuntu/djangoenv/lib/python3.5/site-packages/google_alerts/google_alerts.py", line 158, in authenticate
    raise InvalidCredentials("Email or password was incorrect.")
google_alerts.google_alerts.InvalidCredentials: Email or password was incorrect.
` @9b 

we using the latest code but it is working fine in local server (localhost) but not in production server (live)

**Comment by 9b** [comment]
Sorry, I am not able to help here without more details, especially if it's working on one server and not the other. Try setting `ga.set_log_level('DEBUG')` to show more detail.

**Comment by prakasharul** [comment]
Its okay pal, thanks for your effort.

I think this issue with Google security. the google account which I am
currently using is Indian based, but the server location is the United
States, so I am getting security alerts from Google. they are preventing
the login in the server.
