### ISSUE TITLE
Cannot get alerts list or create new alerts

### ISSUE THREAD

**Issue by gcmroi** [9b/google-alerts#6]
Hi.

I have been using the library for a while successfully, but a few days ago it started to get errors with `ga.list()` and `ga.create().`

I am using the latest version of the library (0.1.8) and have tried authorizing with several email accounts, always with the same result. I am using Python 2.7.

Here is an output from a debug session:

`DEBUG __init__:_process_state():219 2018-08-12 13:18:38,700| Capturing state from the request`
`DEBUG __init__:_process_state():228 2018-08-12 13:18:41,685| State value set: [None, None, [None, None, None, [None, None, u'com', [None, u'en', u'US']], None, 3, [[None, 1, u'', [None, None, 20], 2, u'en-US', None, None, None, None, None, u'0', None, None, u'AB2Xq4hcilCERh73EFWJVHXx-io2lhh1EhC8UD8']]], u'', None, None, [None, [[None, None, None, 2]]]]`
`INFO  __init__:list():313 2018-08-12 13:18:41,686| No monitors have been created yet.`
`[]`
`DEBUG __init__:_process_state():219 2018-08-12 13:18:41,686| Capturing state from the request`
`DEBUG __init__:_process_state():228 2018-08-12 13:18:43,744| State value set: [None, None, [None, None, None, [None, None, u'com', [None, u'en', u'US']], None, 3, [[None, 1, u'', [None, None, 20], 2, u'en-US', None, None, None, None, None, u'0', None, None, u'AB2Xq4hcilCERh73EFWJVHXx-io2lhh1EhC8UD8']]], u'', None, None, [None, [[None, None, None, 2]]]]`
`INFO  __init__:list():313 2018-08-12 13:18:43,744| No monitors have been created yet.`
`DEBUG __init__:create():345 2018-08-12 13:18:43,744| Creating alert using: https://www.google.com/alerts/create?x=`

I should clarify that there are several alerts in the account I'm using, and the account is enabled and the alerts working.

I would appreciate any insights you might be able to share.

Cheers!

**Comment by 9b** [comment]
Does it appear like you have a valid cookie within `~/.config/google_alerts/session` and the configuration is populated, `~/.config/google_alerts/config.json`

**Comment by gcmroi** [comment]
It looked like I did, but when I tried recreating the cookie and the `config.json` files to see if that exposed other issues  I started getting the following error.

`google_alerts.InvalidCredentials: Email or password was incorrect.`

even if email and pw used in the python file are correct.

Can this be due to having multiple Google account associated with my Chrome browser?

Thanks,

- GC

**Comment by 9b** [comment]
I'd clear those configurations out and run the setup process again to associate your username and password, so the encoder obfuscates the password properly. From there, I would try again and see what shows up. If it errors out because a captcha, we should be able to see that in the logs. 

Make sure to set logs to debug, `ga.set_log_level('DEBUG')`, so we can get the full dump.

**Comment by gcmroi** [comment]
Thanks Brandon. I did remove the configurations and re-run the code with DEBUG mode turned on. Here's the output:

`/usr/local/bin/python3.6 "/Users/gcmroi/Desktop/PyCharm `Projects/google-alerts-master/alert_test.py"`
`DEBUG` __init__:_session_check():174 2018-08-12 16:49:39,974| Session file does not exist
Traceback (most recent call `last):`
  `File` "/Users/gcmroi/Desktop/PyCharm Projects/google-alerts-master/alert_test.py", line 10, in `<module>`
    `ga.authenticate()`
  `File "/Users/gcmroi/Desktop/PyCharm Projects/google-alerts-master/google_alerts/__init__.py", line 284, in `authenticate`
    `raise` InvalidCredentials("Email or password was `incorrect.")`
`google_alerts.InvalidCredentials:` Email or password was `incorrect.`

`Process` finished with exit code 1`

It would seem an issue with the authorization process?

**Comment by 9b** [comment]
Seems like it. Lets try this:

1. Cat out your `config.json` file and copy the password value. 
2. Copy this function, https://github.com/9b/google-alerts/blob/master/google_alerts/cli/manage.py#L28-L56
3 Call it with `obfuscate(<encoded_password>, 'fetch')` and see if it matches your password

**Comment by gcmroi** [comment]
Here's what I get after doing what you suggest:

$ python obfuscate('YWskSmhOSjIwXzAx', 'fetch')
bash: syntax error near unexpected token `('

**Comment by 9b** [comment]
Do not post your obfuscation here. You will need to enclose the encoded password in quotes.

**Comment by gcmroi** [comment]
OK. I did enclose it in quotes though.

**Comment by 9b** [comment]
It appears there's something messed up with the Python2.7 encoder. It's not storing the password correctly. I will fix this sometime this week, but would strongly suggest you use the Python3 version as I don't intend to maintain 2.7 in the future.

**Comment by gcmroi** [comment]
Sounds good. Thanks Brandon.

**Comment by gcmroi** [comment]
Quick update: I was able to delete and recreate the config / session files using a simple implementation in Python 3.6, which seems to have fixed the session data for my 2.7 version as well.

It seems the de-obfuscation still works in 2.7, so this might only be a temporary workaround, but if someone else gets the same issue, this might work for them as well.

Cheers!

**Comment by 9b** [comment]
Good stuff. I will look at the obfuscation routine for 2.7 and update it to be accurate. Assuming your changes solved the authentication issues?

**Comment by gcmroi** [comment]
It did. I guess once the config files got reestablished correctly through the 3.6 routine everything started working again.

Thanks again for jumping on this!
