### ISSUE TITLE
Authentication Failed [google_alerts.AccountCaptcha]

### ISSUE THREAD

**Issue by PremNarain-60258** [9b/google-alerts#8]
google_alerts.AccountCaptcha: Google is forcing a CAPTCHA. To get around this issue, authenticate within your web browser, pass the CAPTCHA and try to run this script again. Once authenticated, this module will cache your session and load that in the future.

**Comment by 9b** [comment]
What this tells me is that the CAPTCHA is more around the account and less on the session itself, good to know. Thanks for sending this over!
